# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# list.py
# Created on: 2014-02-27 09:13:23.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: list <Service_List> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("F:/temp/ServerAdminToolkit/Server Admin Toolkit.tbx")

# Script arguments
Service_List = arcpy.GetParameterAsText(0)

# Local variables:
Server_Name = "myServer"
Port = "6080"
Admin_User = "admin"
Admin_Password = "admin"

# Process: Stop, Start, Delete Services
arcpy.gp.toolbox = "F:/temp/ServerAdminToolkit/Server Admin Toolkit.tbx";
# Warning: the toolbox F:/temp/ServerAdminToolkit/Server Admin Toolkit.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.StopStartService(...) with arcpy.StopStartService_ALIAS(...)
arcpy.gp.StopStartService(Server_Name, Port, Admin_User, Admin_Password, "Stop", Service_List)

