# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# stopPWService.py
# Created on: 2014-02-27 15:20:02.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("F:/temp/ServerAdminToolkit/Server Admin Toolkit.tbx")


# Local variables:

# Process: Stop, Start, Delete Services
arcpy.gp.toolbox = "F:/temp/ServerAdminToolkit/Server Admin Toolkit.tbx";
# Warning: the toolbox F:/temp/ServerAdminToolkit/Server Admin Toolkit.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.StopStartService(...) with arcpy.StopStartService_ALIAS(...)
arcpy.gp.StopStartService("dggissrv2", "6080", "siteadmin", "gisserver2", "Stop", "PublicWorks//Section.MapServer;PublicWorks//SectionCorner.MapServer")

